
package InterfaceGrafica;

import javax.swing.JDesktopPane;


public class OpcaoCadastroPFOuPJ extends javax.swing.JInternalFrame {

    JDesktopPane desktop;
    CadastroPessoaFisica cadastroPF;
    CadastroPessoaJuridica cadastroPJ;
    
    public OpcaoCadastroPFOuPJ(JDesktopPane desktop,CadastroPessoaFisica cadastroPF,CadastroPessoaJuridica cadastroPJ) {
        initComponents();
        this.desktop = desktop;
        this.cadastroPF = cadastroPF;
        this.cadastroPJ = cadastroPJ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCadastroPF = new javax.swing.JButton();
        btnCadastroPJ = new javax.swing.JButton();

        setClosable(true);
        setTitle("Opção Cadastro");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BytebankLogo2.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Selecione uma opção para realizar o Cadastro:");

        btnCadastroPF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCadastroPF.setText("Pessoa Física");
        btnCadastroPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroPFActionPerformed(evt);
            }
        });

        btnCadastroPJ.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCadastroPJ.setText("Pessoa Jurídica");
        btnCadastroPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroPJActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastroPF, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnCadastroPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastroPF, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastroPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroPFActionPerformed
        desktop.add(cadastroPF);
        desktop.setVisible(true);
    }//GEN-LAST:event_btnCadastroPFActionPerformed

    private void btnCadastroPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroPJActionPerformed
        desktop.add(cadastroPJ);
        desktop.setVisible(true);
    }//GEN-LAST:event_btnCadastroPJActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroPF;
    private javax.swing.JButton btnCadastroPJ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
